# ===================================================
# meta infos
# ===================================================
meta:
  project: ads-service-modules
  include:
    - dobi.yaml
    - version.yaml
    - ads-node-module/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=build:
  tasks:
    - build-ads-node-module
    - image-ads-node-module
  annotations:
    description: "[alias] build all"
    tags:
      - alias

alias=deploy:
  tasks:
    - image-ads-node-module:push
  annotations:
    description: "[alias] push all"
    tags:
      - alias
