# ===================================================
# meta infos
# ===================================================
meta:
  project: ads-service-modules
  include:
    - dobi.yaml
    - version.yaml
    - ads-node-module/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=build:
  tasks:
    - build-ads-node-module
    - build-and-push-image-ads-node-module
  annotations:
    description: "[alias] build (and push) all"
    tags:
      - alias
